// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWznAyka7vLzGpAUYSpqjs1i0h5Jrlsk',
    appId: '1:899871612046:web:57178096475352a90bfddf',
    messagingSenderId: '899871612046',
    projectId: 'fitness-tracker-62c7e',
    authDomain: 'fitness-tracker-62c7e.firebaseapp.com',
    storageBucket: 'fitness-tracker-62c7e.firebasestorage.app',
    measurementId: 'G-4FBTV6XDD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTpQK4mKKzHygWDuoKCQ7Dt8RAsIXpJo',
    appId: '1:899871612046:android:6f250576f3e473140bfddf',
    messagingSenderId: '899871612046',
    projectId: 'fitness-tracker-62c7e',
    storageBucket: 'fitness-tracker-62c7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYXsea9aU1hw56w5vNak6CCy_4xpNBNo',
    appId: '1:899871612046:ios:a304338ff19875220bfddf',
    messagingSenderId: '899871612046',
    projectId: 'fitness-tracker-62c7e',
    storageBucket: 'fitness-tracker-62c7e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBYXsea9aU1hw56w5vNak6CCy_4xpNBNo',
    appId: '1:899871612046:ios:a304338ff19875220bfddf',
    messagingSenderId: '899871612046',
    projectId: 'fitness-tracker-62c7e',
    storageBucket: 'fitness-tracker-62c7e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxWznAyka7vLzGpAUYSpqjs1i0h5Jrlsk',
    appId: '1:899871612046:web:54db28a03e25f3b70bfddf',
    messagingSenderId: '899871612046',
    projectId: 'fitness-tracker-62c7e',
    authDomain: 'fitness-tracker-62c7e.firebaseapp.com',
    storageBucket: 'fitness-tracker-62c7e.firebasestorage.app',
    measurementId: 'G-03KQSWJQLV',
  );
}
